/*
CREATE TABLE CUSTOMER_TABLE(
CUSTOMER_ID   NUMBER(4)   PRIMARY KEY,
CUSTOMER_NAME NUMBER(15)  NOT NULL,
AGE           NUMBER(2)   NOT NULL,
SEX           VARCHAR2(1) NOT NULL
);


CREATE TABLE PRODUCT_GROUP_DIMENSION(
PRODUCT_GROUP_ID    NUMBER(4)    PRIMARY KEY NOT NULL,
PRODUCT_GROUP_CODE  VARCHAR2(5)  NOT NULL,
PRODUCT_GROUP_NAME  VARCHAR2(20) NOT NULL,
CUSTOMER_ID         NUMBER(4)    REFERENCES CUSTOMER_TABLE(CUSTOMER_ID)
);



CREATE TABLE PRODUCT_DIMENSION(
PRODUCT_ID                NUMBER(4)    PRIMARY KEY NOT NULL,
PRODUCT_CODE              VARCHAR2(5)  NOT NULL,
PRODUCT_NAME              VARCHAR2(15) NOT NULL,
PRODUCT_DESC              VARCHAR2(25) NOT NULL,
DEPARTMENT                VARCHAR2(11) NOT NULL,
INITIAL_PRICE             NUMBER(8,2)  NOT NULL,
RETAIL_PRICE              NUMBER(8,2)  NOT NULL,
TARGET_AGE_DEMOGRAPHIC    VARCHAR2(15) NOT NULL
);

CREATE TABLE STORE_DIMENSION(
STORE_ID   NUMBER(4)     PRIMARY KEY NOT NULL, 
STORE_CODE VARCHAR2(4)   NOT NULL,
ADDRESS    VARCHAR2(20)  NOT NULL,
CITY       VARCHAR2(15)  NOT NULL,
PROVINCE   VARCHAR2(15)  NOT NULL
);




CREATE TABLE SALES_FACT_TABLE(
SALES_ID              NUMBER(4)    PRIMARY KEY NOT NULL,
PRODUCT_GROUP_ID      NUMBER(4)    REFERENCES  PRODUCT_GROUP_DIMENSION(PRODUCT_GROUP_ID) NOT NULL,
PRODUCT_ID            NUMBER(4)    REFERENCES  PRODUCT_DIMENSION(PRODUCT_ID)             NOT NULL,
STORE_ID              NUMBER(4)    REFERENCES  STORE_DIMENSION(STORE_ID)                 NOT NULL,
NUM_UNITS_SOLD        NUMBER(4)    NOT NULL,
REVENUE               NUMBER(8,2)  NOT NULL,
PROFIT                NUMBER(8,2)  NOT NULL,
DATE_OF_TRANSACTION   DATE         NOT NULL
);


CREATE TABLE LIFE_EXPECTANCY_REFERENCE(
REF_DATE    VARCHAR2(15),
GEO         VARCHAR2(15),
AGE         VARCHAR2(15),
VECTOR      VARCHAR2(15),
COORDINATE  VARCHAR2(15),
VALUE       NUMBER(6,2)
);

CREATE TABLE TOP_FEMALE_REFERENCE_TABLE(
YEAR_TIME  NUMBER(4),
NAME       VARCHAR2(25),
FREQUENCY  NUMBER(5)
);

CREATE TABLE TOP_MALE_REFERENCE_TABLE(
YEAR_TIME  NUMBER(4),
NAME       VARCHAR2(25),
FREQUENCY  NUMBER(5)
);

*/
drop table POPULATION_REFERENCE_TABLE;

CREATE TABLE POPULATION_REFERENCE_TABLE(
REF_DATE                      NUMBER(4),
GEO                           VARCHAR2(15),
GEOGRAPHICAL_CLASSIFICATION   VARCHAR2(35),
pop_id                        NUMBER(6),
SEX                           VARCHAR2(40),
age                           VARCHAR2(20),

VECTOR                        VARCHAR2(25),
COORDINATE                    VARCHAR2(15),
VALUE                         NUMBER(10)                       
);



/*

CREATE TABLE LIFE_EXPECTANCY_REFERENCE(
REF_DATE    VARCHAR2(20),
GEO         VARCHAR2(35),
SEX         VARCHAR2(20),
AGE         VARCHAR2(20),
VECTOR      VARCHAR2(2O),
COORDINATE  VARCHAR2(20),
VALUE       NUMBER(6,2)
);

*/
