/*
drop table LIFE_EXPECTANCY_REFERENCE;


CREATE TABLE LIFE_EXPECTANCY_REFERENCE(
REF_DATE    VARCHAR2(20),
GEO         VARCHAR2(35),
SEX         VARCHAR2(20),
AGE         VARCHAR2(20),
VECTOR      VARCHAR2(20),
COORDINATE  VARCHAR2(20),
VALUE       NUMBER(6,2)
);
*/

drop table TOP_FEMALE_REFERENCE_TABLE;
drop table TOP_MALE_REFERENCE_TABLE;

CREATE TABLE TOP_FEMALE_REFERENCE_TABLE(
YEAR_TIME  NUMBER(4),
NAME       VARCHAR2(25),
FREQUENCY  NUMBER(5)
);

CREATE TABLE TOP_MALE_REFERENCE_TABLE(
YEAR_TIME  NUMBER(4),
NAME       VARCHAR2(25),
FREQUENCY  NUMBER(5)
);

