--  Most profitable Customer Name ----------------- 
SELECT NAME,REV_SUM ,PROFIT_SUM
FROM( SELECT CUS.CUSTOMER_NAME NAME,SUM(F.REVENUE) REV_SUM,SUM(F.PROFIT ) PROFIT_SUM 
      FROM SALES_FACT_TABLE F
 
      INNER JOIN CUSTOMER_TABLE CUS
      ON CUS.CUSTOMER_ID=F.SALES_ID
      GROUP BY CUS.CUSTOMER_NAME)
ORDER BY REV_SUM DESC, PROFIT_SUM DESC;


-- LEAST profitable Customer Name ----------------- 
SELECT NAME,REV_SUM ,PROFIT_SUM
FROM( SELECT CUS.CUSTOMER_NAME NAME,SUM(F.REVENUE) REV_SUM,SUM(F.PROFIT ) PROFIT_SUM 
      FROM SALES_FACT_TABLE F
 
      INNER JOIN CUSTOMER_TABLE CUS
      ON CUS.CUSTOMER_ID=F.SALES_ID
      GROUP BY CUS.CUSTOMER_NAME)
ORDER BY REV_SUM ASC, PROFIT_SUM ASC;