--  Most profitable GENDER ----------------- 
SELECT SEX REV_SUM ,PROFIT_SUM
FROM( SELECT CUS.SEX SEX,SUM(F.REVENUE) REV_SUM,SUM(F.PROFIT ) PROFIT_SUM 
      FROM SALES_FACT_TABLE F
 
      INNER JOIN CUSTOMER_TABLE CUS
      ON CUS.CUSTOMER_ID=F.SALES_ID
      GROUP BY CUS.SEX)
ORDER BY REV_SUM DESC, PROFIT_SUM DESC;