SELECT PRODUCT,REV_SUM ,PROFIT_SUM
FROM( SELECT PD.PRODUCT_NAME PRODUCT, SUM(F.REVENUE) REV_SUM, SUM(F.PROFIT ) PROFIT_SUM 
      FROM SALES_FACT_TABLE F
 
      INNER JOIN PRODUCT_DIMENSION PD
      ON PD.PRODUCT_ID=F.PRODUCT_ID
      
      GROUP BY PD.PRODUCT_NAME)
ORDER BY REV_SUM DESC, PROFIT_SUM DESC;
      