SELECT CONCAT('$',F.REVENUE) AS "PROFIT",PD.PRODUCT_NAME AS "PRODUCT",PG.PRODUCT_GROUP_NAME AS "AGE GROUP",ST.CITY ,F.DATE_OF_TRANSACTION AS "DATE"
FROM SALES_FACT_TABLE F

INNER JOIN PRODUCT_GROUP_DIMENSION PG
ON PG.PRODUCT_GROUP_ID=F.PRODUCT_GROUP_ID

INNER JOIN PRODUCT_DIMENSION PD
ON PD.PRODUCT_ID=F.PRODUCT_ID

INNER JOIN STORE_DIMENSION ST
ON ST.STORE_ID=F.STORE_ID

ORDER BY F.REVENUE DESC;